= Octobre - 2023

== Week 1 : 02/10/2023 - 06/10/2023
:stem: latexmath
:xrefstyle: short
:sectiondir: abstracts/week_1/
*Réunions :*

*  _Lundi matin_ -  Présentation de Hugo Talbot sur la méthodes des éléments finis
*  _Mardi matin_ - Réunion d'équipe (oubliée)

*Fait durant la semaine :*

*  modification du rapport de stage avec les remarques de Michel
*  lecture de l'article 2104.08426 : "Exact imposition of boundary conditions with distance functions in physics-informed deep neural networks"; lecture jusqu'à la page 23, il ne reste plus que les résultats numérique
*  reproduction de certains résultats de l'article, notamment : calcul de la fonction distance sur un segment et un triangle (2 méthodes)


*A faire :*

*  réécouter vocal réunion et prendre des notes clairs de ce qu'on me demande !
*  essayer de calculer une distance _signée_
*  reproduire certains des résultats avec le PINNs présentés dans l'article
*  récupérer repo git ScimBa et regarder les issues !

== Week 2 : 09/10/2023 - 13/10/2023
:stem: latexmath
:xrefstyle: short
:sectiondir: abstracts/week_2/
*Réunions :*

*  _Mardi matin_ -  Réunion d'équipe - Présentation de Pablo
*  _Vendredi matin_ - TP d'Informatique L2S3

*Fait durant la semaine :*

*  sampling dans Scimba dans un domaine créé par une fonction distance signée (SD) et sampling sur le bord
*  entraînement du PINNs à apprendre stem:[u] et comparaison en apprenant stem:[w] -> application de la correction par addition avec FEM et stem:[\phi]-FEM sur le cercle
*  organisation du code :

*  création d'un document latex pour expliquer le problème considéré
*  homogénéisation du code (pas de copies des paramètres, des fonctions...)
*  création d'un script python qui permette de lancer le PINNs avec différentes configurations (paramètres en arguments, sauvegarde du modèle)
*  création d'un script python qui permette de créer un tableur qui regroupe toutes les configurations choisies



*A faire :*

*  ajout des images résultats dans le fichier excel (training ?)
*  organisation de la partie correction avec sauvegarde des images
*  reproduire certains des résultats avec le PINNs présentés dans l'article ?
*  continuer lecture article 2104.08426

== Week 3 : 16/10/2023 - 20/10/2023
:stem: latexmath
:xrefstyle: short
:sectiondir: abstracts/week_3/
*Réunions :*

*  _Mardi matin_ -  Réunion d'équipe - Tour de table
*  _Vendredi matin_ - TP d'Informatique L2S3

*Fait durant la semaine :*

*  test MVP sur un polygone "aléatoire" créé à partir des coordonnées polaires d'un cercle centré en stem:[(x_0,y_0)]
*  réorganisation/homogénéisation du code pour :

*  l'ajout de la variation du second membre stem:[f]
*  la création de classes avec les problèmes considérés (Circle, Polygon.. avec les fonctions phi,u_ex... associées)
*  la sauvegarde des modèles (réorganisation des dossiers pour networks)

*  Tentative d'entraînement sur un Polygone (au lieu du cercle) -> non fructueux pour le moment (fonctionne avec le même code sur un carré mais pas sur le polygone ?). On utilise la fonction distance signée calculée par MVP à partir des points du polygone (comme présentée dans l'article 2104.08426) \textcolor{red}{-> test inutile : on veut entraîner le réseau à apprendre stem:[\phi w] sur stem:[\Omega_h] où on utilise la fonction distance signée calculée par MVP uniquement pour le sampling des points}


*A faire :*

*  organisation de la partie correction avec sauvegarde des images 
*  lecture article 2301.05187 (WIRE)

== Week 4 : 23/10/2023 - 27/10/2023
:stem: latexmath
:xrefstyle: short
:sectiondir: abstracts/week_4/
*Réunions :*

*  _Lundi après-midi_ - Réunion (Michel + Vanessa)
*  _Mardi matin_ - Réunion d'équipe - Présentation de Diwei
*  _Vendredi matin_ - TP d'Informatique L2S3

*Fait durant la semaine :*

*  Organisation de la partie Correction avec sauvegarde des images - script qui lance la correction à partir d’un modèle donnée
*  Modification du excel avec ajout des résultats de correction...
*  Rectification problème modèle avec variation du terme source f - re-lancement des entraînements
*  Entraînement du modèle à prédire la solution stem:[u=\phi w] sur stem:[\mathcal{O}] -> Correction avec stem:[\phi]-FEM
*  Recalage de la levelset (avec méthode de Killian) -> Entrainement du modèle sur stem:[u] (il n'y a que dans ce cas que le sampling au bord est utilisé) -> Correction avec FEM
*  *Suivi hebdomadaire* avec les résultats obtenus depuis le début
*  Préparation d'un document pour la *réunion* de Lundi prochain avec les nouveaux résultats obtenus


*A faire :*

*  tester méthode de Newton (proposé par Emmanuel par mail) pour recalage de la levelset ?
*  lecture article 2301.05187 (WIRE)

== Week 5 : 30/10/2023 - 03/11/2023
:stem: latexmath
:xrefstyle: short
:sectiondir: abstracts/week_5/
(ABSENTE du Lundi au Mercredi car Malade)

*Réunions :*

*  _Lundi après-midi_ - Réunion (Michel + Vanessa) stem:[\rightarrow] ABSENTE (MALADE)
*  _Mardi matin_ - Réunion d'équipe - ? stem:[\rightarrow] ABSENTE (MALADE)
*  _Vendredi matin_ - TP d'Informatique L2S3 stem:[\rightarrow] NON (Vacance scolaire)
*  _Vendredi après-midi_ - Réunion (Michel)

*Fait durant la semaine :*

*  Lecture de l'article 2301.05187 (WIRE)
*  Bibliographie (recherche de papier sur les INR)
*  Projection des solutions stem:[\phi]-FEM sur stem:[\Omega] pour le calcul des erreurs


*A faire :*

*  Lire nouvel article 2006.09661 ("Implicit Neural Representations with Periodic Activation Functions")
*  Préparer document résultats stem:[\rightarrow] réunion Lundi 06/11/2023

